# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgencyRc < Formula
  include Language::Python::Virtualenv

  desc "Agency — An operating system for AI agents (release candidate)"
  homepage "https://github.com/geoffbelknap/agency"

  bottle do
    root_url "https://github.com/geoffbelknap/homebrew-tap/releases/download/agency-rc-0.3.19-rc1"
    rebuild 1
    sha256 cellar: :any_skip_relocation, x86_64_linux: "d4a75160750edeb9dcfeccc1adef46cdaefa95f0b5cfe9b6a544a21c3adbee40"
  end

  depends_on "e2fsprogs"
  depends_on "geoffbelknap/tap/microagent-kit"
  depends_on "python@3.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency_0.3.19-rc1_darwin_amd64.tar.gz"
      sha256 "2666aedc967e413f72751931a734d1939e7d700432d0ad96eb49f23df83bbbcf"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency_0.3.19-rc1_darwin_arm64.tar.gz"
      sha256 "3bb0f08580e853947f1e13b19cfee00753c2391b29353d5f486a52145342c13e"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency_0.3.19-rc1_linux_amd64.tar.gz"
      sha256 "a8ea9fcfaead170ee8b71c936697ef0c52026c1e261e1b7a73b2526e7f675321"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency_0.3.19-rc1_linux_arm64.tar.gz"
      sha256 "f14340cc5aff989a7696a3d95569c619d097db83602faf09d51e9ce134504a04"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  conflicts_with "agency"

  preserve_rpath
  skip_clean "libexec/venv"

  resource "python-wheelhouse-darwin-arm64" do
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency-python-wheelhouse-darwin-arm64.tar.gz"
        sha256 "d093ea6ea815a644c1ac2e59d535b3e4f3f7796025b701318175f0943a1b818b"
      end
    end
  end

  resource "python-wheelhouse-darwin-amd64" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency-python-wheelhouse-darwin-amd64.tar.gz"
        sha256 "82be64fac29ba12f39997e9bb5be80fd76fe6ec8c7c72a435c38a1a85aa0920b"
      end
    end
  end

  resource "python-wheelhouse-linux-amd64" do
    on_linux do
      if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency-python-wheelhouse-linux-amd64.tar.gz"
        sha256 "f5f244830e854b990b187897d055f0832933daa7e47056aabacf5d8a0c12ee9c"
      end
    end
  end

  resource "python-wheelhouse-linux-arm64" do
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc1/agency-python-wheelhouse-linux-arm64.tar.gz"
        sha256 "226a3c0231bc92a78052cc4c96a398846b1c5103b3cbf0b3a6a88359b0c0f5d6"
      end
    end
  end

  def caveats
    <<~EOS
      This formula installs the Agency release-candidate channel.
      It conflicts with the stable agency formula because both install `agency`.

      Start Agency with:

        agency quickstart

      On Linux and WSL2, Agency uses microagent with Firecracker. `agency
      quickstart` and `agency admin doctor` check whether the current user can
      open /dev/kvm read/write. To check manually before quickstart, run:

        test -r /dev/kvm && test -w /dev/kvm

      If that command fails or Agency reports KVM access failure, run:

        sudo usermod -aG kvm $USER

      On regular Linux, log out and back in so the new group membership is
      applied. On WSL2 only, run this from Windows, then reopen the distro:

        wsl.exe --shutdown
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
