# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agency < Formula
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"
  version "0.3.7"

  depends_on "e2fsprogs"
  depends_on "geoffbelknap/tap/microagent-kit"
  depends_on "python@3.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.7/agency_0.3.7_darwin_amd64.tar.gz"
      sha256 "50f97d624773df22d4bbbcde92af242c83c9d32814be605d92b728a339650ff9"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.7/agency_0.3.7_darwin_arm64.tar.gz"
      sha256 "69c5c03d60d0b9cd0939aebc97db8d4983d825821faefaa57ec293610031cb36"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.7/agency_0.3.7_linux_amd64.tar.gz"
      sha256 "3cd1aac07f55d9004a08c1d4ad69afdfde168be7515de6dce39ff84bae16003f"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.7/agency_0.3.7_linux_arm64.tar.gz"
      sha256 "1915b36f3ec9a2eeb023c89f33b1c9ffa0e0b260ef6898c1d9af3b73378a828a"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  conflicts_with "agency-rc"

  def post_install
    ENV["AGENCY_PYTHON_VENV"] = "#{libexec}/venv"
    system "#{pkgshare}/scripts/install/host-dependencies.sh", "--skip-system-packages"
  end

  def caveats
    <<~EOS
      Start Agency with:

        agency quickstart
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
