# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agency < Formula
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.1.0/agency_0.1.0_darwin_amd64.tar.gz"
      sha256 "9e5d2420c5098fa823a0160247786d22f1c84e49be80639620e035b88ea2da5a"

      define_method(:install) do
        bin.install "agency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.1.0/agency_0.1.0_darwin_arm64.tar.gz"
      sha256 "be34ab29a147ff734cd4ce7e0076280398335ce14f2b46ab8dd7f4b467639b88"

      define_method(:install) do
        bin.install "agency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.1.0/agency_0.1.0_linux_amd64.tar.gz"
      sha256 "a05e5a45d11b20a285a17001ce2198f4b115259d8fd7e5a4f9b1866aa0d03931"
      define_method(:install) do
        bin.install "agency"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.1.0/agency_0.1.0_linux_arm64.tar.gz"
      sha256 "32ac06837eaaf36ef0cd8ef5757071eae4e3706d0e8361e0f41d2d958cf5972c"
      define_method(:install) do
        bin.install "agency"
      end
    end
  end

  def caveats
    <<~EOS
      To get started:

        1. Make sure Docker is running
        2. Get an API key from Anthropic, OpenAI, or Google
        3. Run: agency setup

      Full documentation: https://github.com/geoffbelknap/agency
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
