# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgencyRc < Formula
  include Language::Python::Virtualenv

  desc "Release candidate channel for Agency"
  homepage "https://github.com/geoffbelknap/agency"
  version "0.3.18"

  bottle do
    root_url "https://github.com/geoffbelknap/homebrew-tap/releases/download/agency-rc-0.3.18"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "458fa63bce241b4423501c0d922f254f0d6ce0b286fc7aae82820e072b08b62c"
  end

  depends_on "e2fsprogs"
  depends_on "geoffbelknap/tap/microagent-kit"
  depends_on "python@3.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency_0.3.18_darwin_amd64.tar.gz"
      sha256 "5ba1282cfa4295263b7735649744839f34c16edcb2dcd2c5610c60defa41c816"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency_0.3.18_darwin_arm64.tar.gz"
      sha256 "a472cc151c1e347313ae6c9f28794b67df49eef37cbcf33e6e2c1ed25d798af5"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency_0.3.18_linux_amd64.tar.gz"
      sha256 "66c33e6b52312c6a7c6079c8f7afa2783788548c862eef9592e2a4a793376c82"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency_0.3.18_linux_arm64.tar.gz"
      sha256 "81ea8b15f1cab1eb2a0d7ef14d000b1e9a814513c38e111dd4388364adfb24dc"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  conflicts_with "agency"

  preserve_rpath
  skip_clean "libexec/venv"

  resource "python-wheelhouse-darwin-arm64" do
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency-python-wheelhouse-darwin-arm64.tar.gz"
        sha256 "65061720d93be44af69a3eeb91c836b88dbe2a008bf9ff7a6baeb07ceaff10d0"
      end
    end
  end

  resource "python-wheelhouse-darwin-amd64" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency-python-wheelhouse-darwin-amd64.tar.gz"
        sha256 "66f5499a18ab7aa446a1cb588b861fb9ef5378173ab9f0136ec0c6cac9c2a236"
      end
    end
  end

  resource "python-wheelhouse-linux-amd64" do
    on_linux do
      if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency-python-wheelhouse-linux-amd64.tar.gz"
        sha256 "bc9ab72d7009ee79147185d9791ec1d609a07b7f7c29978faa6c4fb5d1193312"
      end
    end
  end

  resource "python-wheelhouse-linux-arm64" do
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.18/agency-python-wheelhouse-linux-arm64.tar.gz"
        sha256 "d63401981c817b3516c3d07aa6d00fea422c0806e8cc22680a2b214a12ccc360"
      end
    end
  end

  def caveats
    <<~EOS
      This formula installs the Agency release-candidate channel.
      It conflicts with the stable agency formula because both install `agency`.

      Start Agency with:

        agency quickstart

      On Linux and WSL2, Agency uses microagent with Firecracker. `agency
      quickstart` and `agency admin doctor` check whether the current user can
      open /dev/kvm read/write. If either command reports KVM access failure,
      run:

        sudo usermod -aG kvm $USER

      On regular Linux, log out and back in so the new group membership is
      applied. On WSL2 only, run this from Windows, then reopen the distro:

        wsl.exe --shutdown
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
