# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgencyRc < Formula
  desc "Agency — An operating system for AI agents (release candidate)"
  homepage "https://github.com/geoffbelknap/agency"
  version "0.3.19-rc5"

  depends_on "e2fsprogs"
  depends_on "geoffbelknap/tap/microagent"
  depends_on "python@3.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc5/agency_0.3.19-rc5_darwin_amd64.tar.gz"
      sha256 "356c5cb5d4efcec7aafae6f8cfbbadc563e83b8c3c349d655042a899eaa41e59"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        bin.install "agency-host-comms"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-host-comms"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc5/agency_0.3.19-rc5_darwin_arm64.tar.gz"
      sha256 "59c3c2f7650917e12712476440ca24daa2bc92f55bb8e6aa2845e7377c79e442"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        bin.install "agency-host-comms"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-host-comms"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc5/agency_0.3.19-rc5_linux_amd64.tar.gz"
      sha256 "0cf2ac46c9e977df89ca215e20b1b38b7a65c5085dfde1542f8fbad98a4e3607"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        bin.install "agency-host-comms"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-host-comms"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.19-rc5/agency_0.3.19-rc5_linux_arm64.tar.gz"
      sha256 "46297f0817d7c3168440793b572ae465fdf0c501627d3b7b09be72e0ad59be77"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        bin.install "agency-host-comms"
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        (pkgshare/"bin").install_symlink bin/"agency-host-comms"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  conflicts_with "agency"

  # Host Python infrastructure dependencies are hydrated under
  # ~/.agency/infrastructure/python/venv during first run.

  def caveats
    <<~EOS
      This formula installs the Agency release-candidate channel.
      It conflicts with the stable agency formula because both install `agency`.

      Start Agency with:

        agency quickstart

      On first run, Agency hydrates host-managed Python infrastructure
      packages under ~/.agency/infrastructure/python/venv for egress and
      knowledge services.

      Check host readiness with:

        agency admin doctor
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
