# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agency < Formula
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"
  version "0.3.15"

  depends_on "e2fsprogs"
  depends_on "geoffbelknap/tap/microagent-kit"
  depends_on "python@3.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency_0.3.15_darwin_amd64.tar.gz"
      sha256 "29f894033e06b67128b27abb9de0e6a50904c3ab7e05310760e081edaa6eacd7"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency_0.3.15_darwin_arm64.tar.gz"
      sha256 "f658ceb03f645f853ede5cb2843a8695bdd6a1087158df75e622fd5624b17e31"

      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency_0.3.15_linux_amd64.tar.gz"
      sha256 "787ee4ee1d35ced1b4b2b00bc8b810dcc07f8d375fa75cf26d52994208c7a68f"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency_0.3.15_linux_arm64.tar.gz"
      sha256 "3b355e9a665672a9bb5166c201d10c9e45aba44ce82f77a654a878cf9d03c7d4"
      define_method(:install) do
        bin.install "agency"
        bin.install "agency-enforcer-host"
        venv = virtualenv_create(libexec/"venv", "python3.14")
        resources.find(&:url).stage do
          venv.pip_install Pathname.glob("*.whl")
        end
        (pkgshare/"bin").install_symlink bin/"agency-enforcer-host"
        pkgshare.install "bin"
        pkgshare.install "images"
        pkgshare.install "services"
        pkgshare.install "scripts"
        pkgshare.install "web"
      end
    end
  end

  conflicts_with "agency-rc"

  include Language::Python::Virtualenv
  preserve_rpath
  skip_clean "libexec/venv"

  resource "python-wheelhouse-darwin-arm64" do
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency-python-wheelhouse-darwin-arm64.tar.gz"
        sha256 "4ac5a0ff469a20e272169761f2911ed58120a43db6ccb3453b5cb24a468c8eb9"
      end
    end
  end

  resource "python-wheelhouse-darwin-amd64" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency-python-wheelhouse-darwin-amd64.tar.gz"
        sha256 "f9dc663b7f685cb6ab51356d5121d7ce3efcd8d1d3326df2d463c58d2cbde5f0"
      end
    end
  end

  resource "python-wheelhouse-linux-amd64" do
    on_linux do
      if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency-python-wheelhouse-linux-amd64.tar.gz"
        sha256 "23ced6a0c24ea7481b84c953771bba77df1cc8d9556a41eb50739babb0cd9691"
      end
    end
  end

  resource "python-wheelhouse-linux-arm64" do
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/geoffbelknap/agency/releases/download/v0.3.15/agency-python-wheelhouse-linux-arm64.tar.gz"
        sha256 "093e16f4f4bcf5551430f4918712cdcd678b5bcdcb81a6d419266d5426bd6fdc"
      end
    end
  end

  def caveats
    <<~EOS
      Start Agency with:

        agency quickstart
    EOS
  end

  test do
    system "#{bin}/agency", "--version"
  end
end
