# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicrovmRootfs < Formula
  desc "Daemonless OCI-to-ext4 rootfs builder for microVM runtimes"
  homepage "https://github.com/geoffbelknap/microvm-rootfs"
  version "0.1.0"

  depends_on "e2fsprogs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_darwin_amd64.tar.gz"
      sha256 "b3bb7f989ef5382193f9717f1b284dea8a3f49d663d8f5163a953d5384f364ec"

      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_darwin_arm64.tar.gz"
      sha256 "d7a487cfdf4cd821431c18e7a9331d8319f4ed9cf138ce9877dd2fc353339d96"

      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_linux_amd64.tar.gz"
      sha256 "f7883b2a9f4a6a956f81aac7474b36d3a57db876cc9292ef142742493b4c31a5"
      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_linux_arm64.tar.gz"
      sha256 "0687939fa73d163e80f3be8cc52c64d0a7446537a2647d783206b3a99b336335"
      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
  end

  def caveats
    <<~EOS
      microvm-rootfs requires mke2fs. Homebrew installs it through e2fsprogs.

      On macOS, use the Homebrew path explicitly when needed:

        microvm-rootfs --mke2fs #{Formula["e2fsprogs"].opt_sbin}/mke2fs ...
    EOS
  end

  test do
    system bin/"microvm-rootfs", "version"
  end
end
