# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicrovmRootfs < Formula
  desc "Daemonless OCI-to-ext4 rootfs builder for microVM runtimes"
  homepage "https://github.com/geoffbelknap/microvm-rootfs"
  version "0.1.0"

  depends_on "e2fsprogs"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_darwin_amd64.tar.gz"
      sha256 "936f9d6074c76debb8690a6a24b56158352c88556637eb899e951a496a9f9e2d"

      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_darwin_arm64.tar.gz"
      sha256 "1bba761eac6bf89518b1eea47b1ede8c47b1b645a1296649573fd4233e460073"

      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_linux_amd64.tar.gz"
      sha256 "554913e1a003c8df6edb85678598b0a1509597c1f71354c79e35e667ac3f69a4"
      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microvm-rootfs/releases/download/v0.1.0/microvm-rootfs_0.1.0_linux_arm64.tar.gz"
      sha256 "16a7f490dd49192731e6ad6681151cf35439cdb318bb9436d6d4ed2c51e89564"
      define_method(:install) do
        bin.install "microvm-rootfs"
      end
    end
  end

  def caveats
    <<~EOS
      microvm-rootfs requires mke2fs. Homebrew installs it through e2fsprogs.

      On macOS, use the Homebrew path explicitly when needed:

        microvm-rootfs --mke2fs #{Formula["e2fsprogs"].opt_sbin}/mke2fs ...
    EOS
  end

  test do
    system "#{bin}/microvm-rootfs", "version"
  end
end
