# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microagency < Formula
  desc "Governed MCP gateway: cred-blind, off-context tool access for any MCP client"
  homepage "https://github.com/geoffbelknap/microagency"
  version "0.1.2"

  depends_on "microagent"
  depends_on "openbao"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_darwin_amd64.tar.gz"
      sha256 "555b039155cc9c59d9ee6a3833a33d146843890781e6dd728c1ce71640ff8f68"

      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_darwin_arm64.tar.gz"
      sha256 "b655c5f68950767f0b26f293e027be6885bdf456e279493ac8d974eb634b0bff"

      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_linux_amd64.tar.gz"
      sha256 "42a05c7efe8052d08763421e7b814410826f9ec7f02b278267eee9687667d0ba"
      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_linux_arm64.tar.gz"
      sha256 "aa37185caf34d8114ea1eba6adf2247838204f07f315f75760ca8d260dc7539d"
      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  conflicts_with "microagency-latest"

  def caveats
    <<~EOS
      Get started:  microagency up
    EOS
  end

  test do
    system "#{bin}/microagency", "version"
  end
end
