# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicroagencyLatest < Formula
  desc "Governed MCP gateway (latest build from main): cred-blind, off-context MCP access"
  homepage "https://github.com/geoffbelknap/microagency"
  version "0.1.2-latest.1"

  depends_on "microagent"
  depends_on "openbao"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.1/microagency_0.1.2-latest.1_darwin_amd64.tar.gz"
      sha256 "e0775cef2934d2854450eda7e00c51db944023a49d2b8fd3746a5ed297f96d3a"

      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.1/microagency_0.1.2-latest.1_darwin_arm64.tar.gz"
      sha256 "97c297dfb5f76fd7b347a69256c33f207d3c00af67e248c330b14910bb8a7cb4"

      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.1/microagency_0.1.2-latest.1_linux_amd64.tar.gz"
      sha256 "2764bcb015c96850f12b5f1f34e3e50ea5c4ecae409f5fbc3423814b2b94b872"
      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.1/microagency_0.1.2-latest.1_linux_arm64.tar.gz"
      sha256 "33580a50e07dd431513a6645c36e3be4d0421f5ae00f3cdfcee7bffeeee6d5e3"
      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  conflicts_with "microagency"

  def caveats
    <<~EOS
      This is the latest build from main, refreshed on every merge. It conflicts
      with the stable `microagency` formula (both install `microagency`).

      Get started:  microagency up
    EOS
  end

  test do
    system "#{bin}/microagency", "version"
  end
end
