# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicroagencyLatest < Formula
  desc "Governed MCP gateway (latest build from main): cred-blind, off-context MCP access"
  homepage "https://github.com/geoffbelknap/microagency"
  version "0.1.2-latest.7"

  depends_on "microagent"
  depends_on "openbao"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.7/microagency_0.1.2-latest.7_darwin_amd64.tar.gz"
      sha256 "fbd612ea4cf73c4d932d2a4ff04801fd3cdd94d2d28bc96874799950da3931f4"

      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.7/microagency_0.1.2-latest.7_darwin_arm64.tar.gz"
      sha256 "bcb74e98a2a3d466c8392b36c7683c18b5fe3f88c68c2835e9fd0fd4b1529937"

      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.7/microagency_0.1.2-latest.7_linux_amd64.tar.gz"
      sha256 "3f49f2c27d432e50364f93f571ce33fe838ccfc362ed466819c069064308ba82"
      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2-latest.7/microagency_0.1.2-latest.7_linux_arm64.tar.gz"
      sha256 "72882e9bf5ecc028f9d2cc3d24c7148ab4f50d9b78958acf00014fa23308e271"
      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  conflicts_with "microagency"

  def caveats
    <<~EOS
      This is the latest build from main, refreshed on every merge. It conflicts
      with the stable `microagency` formula (both install `microagency`).

      Get started:  microagency up
    EOS
  end

  test do
    system "#{bin}/microagency", "version"
  end
end
