# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Microagency < Formula
  desc "Governed MCP gateway: cred-blind, off-context tool access for any MCP client"
  homepage "https://github.com/geoffbelknap/microagency"
  version "0.1.2"

  depends_on "microagent"
  depends_on "openbao"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_darwin_amd64.tar.gz"
      sha256 "41631a425fc6731c673c4c1e84f3b710820a807a744976b55626ea1762d7ab56"

      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_darwin_arm64.tar.gz"
      sha256 "da7b1b49475a410545d6754095ba849c16c5a956502392a5c9ab58d881399ed6"

      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_linux_amd64.tar.gz"
      sha256 "3c890d65848dad52aebb922e0204f3077fb9a80f7a803f10d02f1e28f0378c7a"
      define_method(:install) do
        bin.install "microagency"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/geoffbelknap/microagency/releases/download/v0.1.2/microagency_0.1.2_linux_arm64.tar.gz"
      sha256 "d4a16edef34c4573c872fa16f3317119028d1272993003fea54c66b1504d8684"
      define_method(:install) do
        bin.install "microagency"
      end
    end
  end

  conflicts_with "microagency-latest"

  def caveats
    <<~EOS
      Get started:  microagency up
    EOS
  end

  test do
    system "#{bin}/microagency", "version"
  end
end
