# This file was generated by GoReleaser. DO NOT EDIT.
cask "agency" do
  version "0.2.0-rc2"

  on_macos do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_amd64.tar.gz"
      sha256 "37b9dd9c6b12fc358a63cf8bd4e6419adeaeb396edb445b262b539079b3de23d"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_arm64.tar.gz"
      sha256 "b68eaf74d1c70c29ffe81911349e0269b3dcb4d7231621ad39cb3a1ac2b95614"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_amd64.tar.gz"
      sha256 "13f5cbd345ea15be3ae5fc085993a5ba7f1c4e1cb7a8f6e5589462856936faaf"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_arm64.tar.gz"
      sha256 "363c6ae38184898e8b640f84c936cdcf48ff8ffa9061ba54dbd7b27c75d00ce1"
    end
  end

  name "agency"
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agency"

  # No zap stanza required

  caveats <<~EOS
    To get started:

      1. Make sure Docker is running
      2. Get an API key from Anthropic, OpenAI, or Google
      3. Run: agency setup

    Full documentation: https://github.com/geoffbelknap/agency
  EOS
end
