# This file was generated by GoReleaser. DO NOT EDIT.
cask "agency" do
  version "0.2.0-rc5"

  on_macos do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_amd64.tar.gz"
      sha256 "012700969905b100b3d05fb6e6a43cbfac09ac25f2e39e6ed960e73678224600"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_arm64.tar.gz"
      sha256 "691de9a71a9de6db4c0f65fb9a5deb3caea4b3b8d8f90f19e9579c6d6e4fcf73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_amd64.tar.gz"
      sha256 "68bf85d13c3e3975b6194092656ccee1c21159798e6e1cc51f5f61e5819c9d62"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_arm64.tar.gz"
      sha256 "697e3ae107d10cfdec70d2aa40f621892c39f3e98243a167db3c8270c0b5fc0c"
    end
  end

  name "agency"
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agency"

  # No zap stanza required

  caveats <<~EOS
    To get started:

      1. Make sure Docker is running
      2. Get an API key from Anthropic, OpenAI, or Google
      3. Run: agency setup

    Full documentation: https://github.com/geoffbelknap/agency
  EOS
end
