# This file was generated by GoReleaser. DO NOT EDIT.
cask "agency" do
  version "0.2.0-rc7"

  on_macos do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_amd64.tar.gz"
      sha256 "203182c45154f33224b8355f67693c8650c0bd61817b99f994a319adf8425d4c"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_darwin_arm64.tar.gz"
      sha256 "62148e700b6c9ccf1cb1d4f52b26e1a764d7dcdc72f041d5ef329f68c5624f1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_amd64.tar.gz"
      sha256 "8fd38cfabe610c99fdd898a23d52cdb64e9f9cd122bfe3b15a5a075bc6ede8a7"
    end
    on_arm do
      url "https://github.com/geoffbelknap/agency/releases/download/v#{version}/agency_#{version}_linux_arm64.tar.gz"
      sha256 "75a9d4d43f501621e05c766b9f2124f252a2ca17fffc9b69e3ba4e905d496513"
    end
  end

  name "agency"
  desc "Agency — An operating system for AI agents"
  homepage "https://github.com/geoffbelknap/agency"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agency"

  # No zap stanza required

  caveats <<~EOS
    To get started:

      1. Make sure Docker is running
      2. Get an API key from Anthropic, OpenAI, or Google
      3. Run: agency setup

    Full documentation: https://github.com/geoffbelknap/agency
  EOS
end
